import React from 'react';
import { PricingSection } from '../components/PricingSection';
import { Link } from 'react-router-dom';

export const PricingPage: React.FC = () => {
  return (
    <main className="pt-24 min-h-screen bg-surface-canvas">
      {/* Page Header */}
      <section className="py-12 bg-gradient-to-b from-[#F0F7F7] to-surface-canvas border-b border-clinical-border/60">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center space-y-4">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-teal-soft text-teal-deep text-xs font-mono font-bold uppercase tracking-wider">
            <span>Transparent Commercial Pricing</span>
          </div>
          <h1 className="font-heading font-extrabold text-3xl sm:text-4xl lg:text-5xl text-content-primary tracking-tight">
            Software Subscriptions for Veterinary Practices
          </h1>
          <p className="text-base sm:text-lg text-content-secondary max-w-2xl mx-auto leading-relaxed">
            Choose monthly or annual access. No per-patient or per-prescription charges.
          </p>

          {/* Unobtrusive Commercial Platform Definition */}
          <div className="max-w-3xl mx-auto mt-6 p-4 rounded-2xl bg-white border border-teal/20 text-xs text-content-secondary shadow-xs">
            <p className="font-medium text-content-primary">
              VetRx is a software platform for veterinary professionals. Subscriptions provide access to VetRx practice-management features for the selected billing period.
            </p>
            <p className="mt-1 text-content-muted">
              VetRx sells software access. VetRx does not provide veterinary treatment, sell veterinary medicines, or act as an animal health service or marketplace.
            </p>
          </div>
        </div>
      </section>

      {/* Main Pricing Cards Component */}
      <PricingSection />

      {/* Distinction Between Software Subscription & Practice Invoicing */}
      <section className="py-16 bg-white border-t border-clinical-border">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="p-8 rounded-3xl bg-slate-50 border border-slate-200/80 shadow-xs space-y-6">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-teal-soft text-teal-deep flex items-center justify-center font-bold text-lg">
                💡
              </div>
              <div>
                <h3 className="font-heading font-bold text-lg sm:text-xl text-content-primary">
                  Understanding VetRx Financial Transactions
                </h3>
                <p className="text-xs text-content-muted">
                  Important clarification on software subscription vs clinic billing
                </p>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 text-xs sm:text-sm">
              <div className="p-5 rounded-2xl bg-white border border-slate-200 space-y-2">
                <span className="font-mono font-bold text-teal-dark uppercase text-[11px] tracking-wider block">
                  Context A: VetRx Subscription Payment
                </span>
                <p className="font-semibold text-content-primary">
                  Veterinarian / Practice → VetRx
                </p>
                <p className="text-content-secondary leading-relaxed">
                  Payment made by the veterinary practitioner or clinic to VetRx for cloud access to practice-management features for the selected monthly or annual billing cycle.
                </p>
              </div>

              <div className="p-5 rounded-2xl bg-white border border-slate-200 space-y-2">
                <span className="font-mono font-bold text-teal-dark uppercase text-[11px] tracking-wider block">
                  Context B: Practice-Generated Client Invoice
                </span>
                <p className="font-semibold text-content-primary">
                  Veterinary Practice → Pet / Animal Owner
                </p>
                <p className="text-content-secondary leading-relaxed">
                  Itemized bills and consultation receipts generated by the practitioner using VetRx for their own client records. VetRx does not collect, receive, or settle client clinical payments.
                </p>
              </div>
            </div>

            <div className="pt-2 flex flex-wrap items-center justify-between gap-4 text-xs font-mono text-content-secondary border-t border-slate-200">
              <span>Need more billing details or tax invoice information?</span>
              <div className="flex gap-4">
                <Link to="/billing" className="text-teal-dark font-semibold hover:underline">
                  Subscription &amp; Billing Guide →
                </Link>
                <Link to="/refund-policy" className="text-teal-dark font-semibold hover:underline">
                  Refund &amp; Cancellation Policy →
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>
    </main>
  );
};
