// ==============================================================================
// VetRx — Centralized Permission Registry & Role-Permission Matrix (Phase 14)
// Authoritative definitions for granular permissions, role resolution, and security.
// ==============================================================================

import { Role, PlatformRole } from '@prisma/client';

export const PERMISSIONS = {
  // Clinical: Patients
  PATIENT_VIEW: 'PATIENT_VIEW',
  PATIENT_CREATE: 'PATIENT_CREATE',
  PATIENT_UPDATE: 'PATIENT_UPDATE',
  PATIENT_DELETE: 'PATIENT_DELETE',

  // Clinical: Animal Owners
  OWNER_VIEW: 'OWNER_VIEW',
  OWNER_CREATE: 'OWNER_CREATE',
  OWNER_UPDATE: 'OWNER_UPDATE',
  OWNER_DELETE: 'OWNER_DELETE',

  // Clinical: Prescriptions
  PRESCRIPTION_VIEW: 'PRESCRIPTION_VIEW',
  PRESCRIPTION_CREATE: 'PRESCRIPTION_CREATE',
  PRESCRIPTION_UPDATE: 'PRESCRIPTION_UPDATE',
  PRESCRIPTION_DELETE: 'PRESCRIPTION_DELETE',

  // Clinical: Formulary / Medicines
  MEDICINE_VIEW: 'MEDICINE_VIEW',
  MEDICINE_CREATE: 'MEDICINE_CREATE',
  MEDICINE_UPDATE: 'MEDICINE_UPDATE',
  MEDICINE_DELETE: 'MEDICINE_DELETE',

  // Clinical: Treatment Packages
  PACKAGE_VIEW: 'PACKAGE_VIEW',
  PACKAGE_CREATE: 'PACKAGE_CREATE',
  PACKAGE_UPDATE: 'PACKAGE_UPDATE',
  PACKAGE_DELETE: 'PACKAGE_DELETE',

  // Clinical & Practice: Invoices / Billing Documents
  INVOICE_VIEW: 'INVOICE_VIEW',
  INVOICE_CREATE: 'INVOICE_CREATE',
  INVOICE_UPDATE: 'INVOICE_UPDATE',
  INVOICE_DELETE: 'INVOICE_DELETE',

  // Clinical Reports
  REPORT_VIEW: 'REPORT_VIEW',

  // Practice & Administration
  PRACTICE_VIEW: 'PRACTICE_VIEW',
  PRACTICE_SETTINGS_MANAGE: 'PRACTICE_SETTINGS_MANAGE',

  // User Management
  USER_VIEW: 'USER_VIEW',
  USER_INVITE: 'USER_INVITE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DEACTIVATE: 'USER_DEACTIVATE',
  USER_REACTIVATE: 'USER_REACTIVATE',

  // Role Management
  ROLE_VIEW: 'ROLE_VIEW',
  ROLE_ASSIGN: 'ROLE_ASSIGN',

  // Security & Audit
  AUDIT_LOG_VIEW: 'AUDIT_LOG_VIEW',

  // Commercial & Subscriptions
  BILLING_VIEW: 'BILLING_VIEW',
  BILLING_MANAGE: 'BILLING_MANAGE',
  SUBSCRIPTION_VIEW: 'SUBSCRIPTION_VIEW',
  SUBSCRIPTION_MANAGE: 'SUBSCRIPTION_MANAGE',

  // Practice Ownership Transfer (Owner Only)
  OWNERSHIP_TRANSFER: 'OWNERSHIP_TRANSFER',

  // Platform Administration (Platform Super Admin Only)
  PLATFORM_PRACTICE_MANAGE: 'PLATFORM_PRACTICE_MANAGE',
  PLATFORM_USER_MANAGE: 'PLATFORM_USER_MANAGE',
  PLATFORM_BILLING_MANAGE: 'PLATFORM_BILLING_MANAGE',
  PLATFORM_AUDIT_VIEW: 'PLATFORM_AUDIT_VIEW',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

// ------------------------------------------------------------------------------
// Authoritative Role -> Permissions Matrix
// ------------------------------------------------------------------------------

const CLINICAL_MUTATION_PERMISSIONS: Permission[] = [
  PERMISSIONS.PATIENT_VIEW,
  PERMISSIONS.PATIENT_CREATE,
  PERMISSIONS.PATIENT_UPDATE,
  PERMISSIONS.PATIENT_DELETE,
  PERMISSIONS.OWNER_VIEW,
  PERMISSIONS.OWNER_CREATE,
  PERMISSIONS.OWNER_UPDATE,
  PERMISSIONS.OWNER_DELETE,
  PERMISSIONS.PRESCRIPTION_VIEW,
  PERMISSIONS.PRESCRIPTION_CREATE,
  PERMISSIONS.PRESCRIPTION_UPDATE,
  PERMISSIONS.PRESCRIPTION_DELETE,
  PERMISSIONS.MEDICINE_VIEW,
  PERMISSIONS.MEDICINE_CREATE,
  PERMISSIONS.MEDICINE_UPDATE,
  PERMISSIONS.MEDICINE_DELETE,
  PERMISSIONS.PACKAGE_VIEW,
  PERMISSIONS.PACKAGE_CREATE,
  PERMISSIONS.PACKAGE_UPDATE,
  PERMISSIONS.PACKAGE_DELETE,
  PERMISSIONS.INVOICE_VIEW,
  PERMISSIONS.INVOICE_CREATE,
  PERMISSIONS.INVOICE_UPDATE,
  PERMISSIONS.INVOICE_DELETE,
  PERMISSIONS.REPORT_VIEW,
  PERMISSIONS.PRACTICE_VIEW,
];

const VIEW_ONLY_PERMISSIONS: Permission[] = [
  PERMISSIONS.PATIENT_VIEW,
  PERMISSIONS.OWNER_VIEW,
  PERMISSIONS.PRESCRIPTION_VIEW,
  PERMISSIONS.MEDICINE_VIEW,
  PERMISSIONS.PACKAGE_VIEW,
  PERMISSIONS.INVOICE_VIEW,
  PERMISSIONS.REPORT_VIEW,
  PERMISSIONS.PRACTICE_VIEW,
];

const STAFF_PERMISSIONS: Permission[] = [
  PERMISSIONS.PATIENT_VIEW,
  PERMISSIONS.PATIENT_CREATE,
  PERMISSIONS.PATIENT_UPDATE,
  PERMISSIONS.OWNER_VIEW,
  PERMISSIONS.OWNER_CREATE,
  PERMISSIONS.OWNER_UPDATE,
  PERMISSIONS.PRESCRIPTION_VIEW, // Cannot create, update, or delete prescriptions
  PERMISSIONS.MEDICINE_VIEW,
  PERMISSIONS.PACKAGE_VIEW,
  PERMISSIONS.INVOICE_VIEW,
  PERMISSIONS.INVOICE_CREATE,
  PERMISSIONS.INVOICE_UPDATE,
  PERMISSIONS.REPORT_VIEW,
  PERMISSIONS.PRACTICE_VIEW,
];

const VETERINARIAN_PERMISSIONS: Permission[] = [
  ...CLINICAL_MUTATION_PERMISSIONS,
  // Veterinarians do not manage users, settings, billing, or ownership
];

const PRACTICE_ADMIN_PERMISSIONS: Permission[] = [
  ...CLINICAL_MUTATION_PERMISSIONS,
  PERMISSIONS.PRACTICE_SETTINGS_MANAGE,
  PERMISSIONS.USER_VIEW,
  PERMISSIONS.USER_INVITE,
  PERMISSIONS.USER_UPDATE,
  PERMISSIONS.USER_DEACTIVATE,
  PERMISSIONS.USER_REACTIVATE,
  PERMISSIONS.ROLE_VIEW,
  PERMISSIONS.ROLE_ASSIGN,
  PERMISSIONS.AUDIT_LOG_VIEW,
  PERMISSIONS.BILLING_VIEW,
  PERMISSIONS.SUBSCRIPTION_VIEW,
  // Note: Explicitly EXCLUDES OWNERSHIP_TRANSFER, BILLING_MANAGE, SUBSCRIPTION_MANAGE
];

const PRACTICE_OWNER_PERMISSIONS: Permission[] = [
  ...PRACTICE_ADMIN_PERMISSIONS,
  PERMISSIONS.BILLING_MANAGE,
  PERMISSIONS.SUBSCRIPTION_MANAGE,
  PERMISSIONS.OWNERSHIP_TRANSFER,
];

export const PLATFORM_SUPER_ADMIN_PERMISSIONS: Permission[] = [
  PERMISSIONS.PLATFORM_PRACTICE_MANAGE,
  PERMISSIONS.PLATFORM_USER_MANAGE,
  PERMISSIONS.PLATFORM_BILLING_MANAGE,
  PERMISSIONS.PLATFORM_AUDIT_VIEW,
];

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [Role.PRACTICE_OWNER]: PRACTICE_OWNER_PERMISSIONS,
  [Role.PRACTICE_ADMIN]: PRACTICE_ADMIN_PERMISSIONS,
  [Role.VETERINARIAN]: VETERINARIAN_PERMISSIONS,
  [Role.STAFF]: STAFF_PERMISSIONS,
  [Role.PRACTICE_STAFF]: STAFF_PERMISSIONS, // Legacy alias
  [Role.READ_ONLY]: VIEW_ONLY_PERMISSIONS,
};

/**
 * Resolves effective permissions for a given practice role.
 */
export function getPermissionsForRole(role: Role | string): Permission[] {
  const normalized = (role === 'PRACTICE_STAFF' ? Role.STAFF : role) as Role;
  return ROLE_PERMISSIONS[normalized] || VIEW_ONLY_PERMISSIONS;
}

/**
 * Checks whether a practice role includes a given permission.
 */
export function roleHasPermission(role: Role | string, permission: Permission | string): boolean {
  const permissions = getPermissionsForRole(role);
  return permissions.includes(permission as Permission);
}
